version: '3.7'

services:

  detecter:
    container_name: detecter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true